AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Runtime: dotnet6
    Timeout: 30
    Tracing: Active
    VpcConfig:
      SecurityGroupIds: !Ref LambdaSecurityGroupIds
      SubnetIds: !Ref LambdaSubnetIds
      
Parameters:
  LambdaSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Subnets to deploy the Lambda function with
  LambdaSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The security groups to assign to the Lambda function
  ProxyArn:
    Type: String
    Description: The ARN of the RDS Proxy to allow permissions to

Resources:
  MinimalGetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DotnetSqlRdsProxy.Api
      Handler: DotnetSqlRdsProxy.Api
      Environment:
        Variables:
          DB_HOST: product-db-proxy.proxy-cojpavfhis28.us-east-2.rds.amazonaws.com
          DB_USER: admin
          DB_NAME: product-db-proxy.proxy-cojpavfhis28.us-east-2.rds.amazonaws.com
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ALL
      Policies:
        - Statement:
            - Sid: AllowRDSProxy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Ref ProxyArn
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"