AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Runtime: dotnet6
    Timeout: 30
    Tracing: Active
    VpcConfig:
      SecurityGroupIds:
      SubnetIds:

Resources:
  MinimalGetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DotnetSqlRdsProxy.Api
      Handler: DotnetSqlRdsProxy.Api
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ALL
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-east-2:521936459218:secret:test/product-db-G1l1Jj
          
            
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"