AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Runtime: dotnet6
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        DB_HOST: !Ref ProxyEndpoint
        DB_USER: admin
        DB_NAME: !Ref ProxyEndpoint
    VpcConfig:
      SecurityGroupIds: !Ref LambdaSecurityGroupIds
      SubnetIds: !Ref LambdaSubnetIds
      
Parameters:
  LambdaSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Subnets to deploy the Lambda function with
  LambdaSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The security groups to assign to the Lambda function
  ProxyArn:
    Type: String
    Description: The ARN of the RDS Proxy to allow permissions to
  ProxyEndpoint:
    Type: String
    Description: The endpoint for the RDS Proxy

Resources:
  MinimalGetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DotnetSqlRdsProxy.Api
      Handler: DotnetSqlRdsProxy.Api
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ALL
      Policies:
        - Statement:
            - Sid: AllowRDSProxy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Ref ProxyArn

  ApplyDatabaseMigrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DotnetSqlRdsProxy.ApplyDbMigrationFunction/
      Handler: DotnetSqlRdsProxy.ApplyDbMigrationFunction
      Policies:
        - Statement:
            - Sid: AllowRDSProxy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Ref ProxyArn
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  DbMigrationFunctionArn:
    Description: "ARN of the apply database migrations function"
    Value: !Ref ApplyDatabaseMigrationsFunction