AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Runtime: dotnet6
    Timeout: 30
    Tracing: Active
    VpcConfig:
      SecurityGroupIds: !Ref LambdaSecurityGroupIds
      SubnetIds: !Ref LambdaSubnetIds
      
Parameters:
  LambdaSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Subnets to deploy the Lambda function with
  LambdaSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The security groups to assign to the Lambda function
  SecretArn:
    Type: String
    Description: The name of the secret holding database credentials

Resources:
  MinimalGetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DotnetSqlRdsProxy.Api
      Handler: DotnetSqlRdsProxy.Api
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretArn
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ALL
      Policies:
        - Statement:
            - Sid: GetSpecificSecret
              Effect: Allow
              Action:
                - secretsmanager:GetResourcePolicy
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecretVersionIds
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
            - Sid: ListSecrets
              Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'
          
            
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"